# Generated by Django 5.1.2 on 2024-10-26 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_rename_createat_task_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="created_at",
            new_name="createdAt",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="updated_at",
            new_name="issueAt",
        ),
    ]
