# Generated by Django 5.1.2 on 2024-10-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0004_rename_createdat_task_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
