# Generated by Django 5.0.7 on 2024-11-01 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0007_cathegorie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cathegorie",
            name="tasks",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="task.task"
            ),
        ),
    ]
