# Generated by Django 5.0.7 on 2024-11-01 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0008_alter_cathegorie_tasks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cathegorie",
            name="tasks",
        ),
        migrations.AddField(
            model_name="task",
            name="cathegorie",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="task.cathegorie",
            ),
        ),
    ]
